name: Deploy to Prod

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - run: echo 'Deployed to test'